### PR TITLE
Added physical resource ID to request object.

### PR DESCRIPTION
**Pull request by rafalwrzeszcz**
According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requests.html in case of UPDATE/DELETE request types, request includes physical resource ID that can identify existing resource. It's very needed in many update scenarios to update subject of changes.

### CODE REVIEW

**Comment by jhovell** [comment]
@rafalwrzeszcz I believe we already have support for PhysicalResourceId - it is an optional parameter on the `send(...)` method. Please see:

https://github.com/SunRun/cfn-response-java/blob/master/src/main/java/com/sunrun/cfnresponse/CfnResponseSender.java#L52

and let me know if this meets your needs.

It's been a little while since I have looked at this project but I believe physicalResourceId was set as a method parameter to mimic the syntax/style of the Node and Python versions of this library (check out the references section of the README in this project for the Node documentation). The 3rd party Python version has an optional parameter as well.

https://github.com/jorgebastida/cfn-response/blob/master/cfnresponse.py#L14

Let me know if this existing functionality does not address your issue and if so we can discuss this fix.

**Comment by rafalwrzeszcz** [comment]
This the request property, sent with UPDATE and DELETE requests. That's the way consecutive calls can track same resource.

**Comment by jhovell** [comment]
Oh, I understand.  Weird I guess we should have added this when we added support for physical resource IDs. I'd like to make sure the behavior as the same as the other languages. 

Since we are adding the physical resource ID to the request (which is sent as a parameter to `send()`) I am wondering if there should be logic added to either set physical resource ID in the response if it is present in the request. I cannot imagine a scenario where you would want to send a different physical resource ID if it was present in the request (UPDATE and DELETE of course. For CREATE it will not be present in request and needs to be added).

Do you happen to know the behavior of the AWS provided Node cfn-response or Python packages (cfnresponse)? Probably also need to update documentation, testing and bump to next maven version.

I can take care of this eventually or if you can provide sooner I can merge and release.

**Comment by rafalwrzeszcz** [comment]
I wouldn't make that assumption. This is how CloidFormation decides if old resource needs to be removed. For example is someone changed custom resource properties and renamed (let's follow my example) Organizational Unit, I need to create a new one and return new physical ID. Then CloudFormation sees difference in IDs and sends `Delete` to my resource handler with old ID in `UPDATE_COMPLETE_CLEANUP` phase.

However we can make it a default fallback, what do you prefer?

**Comment by rafalwrzeszcz** [comment]
BTW - here is a description of this aspect: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html#w2ab1c21c10c57c19c19

**Comment by jhovell** [comment]
@rafalwrzeszcz thanks for the clear explanation. I understand now. I'd rather not speculate further as since it's not documented we'd need to test the Amazon libraries to discover the behavior which I don't have time to do right now. Seems weird but I guess this library doesn't really ever do anything with that value. Could think of ways to test it later.

Only thing I think you could add is a `@Nullable` annotation on the member, getter and setter so that a user of this library would be sure to null-check the value & could take advantage of any static analysis tools for that as well.

**Pull request merged**
