### PR TITLE
Added NoEcho for security such as passwords. See

### PR DESCRIPTION
**Pull request by jgyorffy**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-create.html

### CODE REVIEW

**Comment by jgyorffy** [comment]
I need the NoEcho for passwords. Please see:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-create.html

**Comment by jhovell** [comment]
Hey thanks for the contribution @jgyorffy 

My feedback:
1. Should we add a simple unit test for our new method `send(..., noEcho)` (with the value set to `true`)?
2. Is there a reason to use `Boolean` rather than `boolean` as the type for your new field in CfnResponse (as well as the new send method)? I don't think Jackson was configured to ignore non-null fields, and in any case the two send methods appear to always set to either explicitly true or false. Making it a primitive might (ever so slightly) make it less confusing to a future reader & avoid null object anti-pattern as well as that ? : ternary operator.

If you don't mind we should probably bump the version to 1.1.0 also to reflect the new functionality (rather than patch release).

Other than that, looks good, thanks again for helping out.

**Comment by jgyorffy** [comment]
Can we use a builder pattern for request and just pass in the request object?

⁣Sent from BlueMail ​

**Comment by jgyorffy** [comment]
Yes, should be primitive boolean. Default is false which is ok

⁣Sent from BlueMail ​

**Comment by jhovell** [comment]
@jgyorffy I'd prefer a builder pattern too, or even better an immutable bean constructor, but as this is a very simple library that should be easy for Java novices to use, I am trying to preserve the look-and-feel of this API to be as similar as possible to the Python and NodeJS implementations that are provided by AWS already. You can see from their docs here they both have a `send(...)` method with a number of parameters. In fact ideally we'd preserve the order of parameters as well but maybe I am being too nit-picky. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html

I see your point though; since Java does not have optional parameters maybe a builder pattern or other request object might be better, if Cfn continues to add more optional parameters then maybe the trade off is worth it. I'd say merge what we have for now unless you feel very strongly. You could also mark the old method deprecated so I can remove if we just switch to a builder pattern in the future.

Which reminds me do you also mind updating the README / doc on how to use your new feature?

**Comment by jgyorffy** [comment]
I made the changes. Ready for review.

**Comment by jgyorffy** [comment]
Any idea when this can be release to the main repo in Maven? We need it for our next sprint. Thanks

**Comment by jhovell** [comment]
@jgyorffy just merged & pushed to Maven Central. In my experience it takes at least a few hours to get reflected there, but if you don't see the artifact available by end of the day give me a ping

https://mvnrepository.com/artifact/com.sunrun/cfn-response

Thanks for the contribution 👍

**Pull request merged**
